# Generated by Django 3.2.13 on 2023-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumers', '0002_auto_20230310_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='نام واحد تجاری')),
                ('capacity', models.IntegerField(verbose_name='مقدار تخصیص یافته')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=12, verbose_name='تلفن تماس')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('consumer', models.ManyToManyField(related_name='plans', to='consumers.Consumers', verbose_name='مصرف کننده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
