# Generated by Django 4.1.7 on 2023-03-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='sale_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='sales.salesplan', verbose_name='طرح فروش'),
        ),
    ]
