# Generated by Django 3.2.13 on 2023-03-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20230310_1324'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplan',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات طرح'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='consumers.consumers', unique=True, verbose_name='مصرف کننده'),
        ),
    ]
