# Generated by Django 4.1.7 on 2023-03-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20230310_1324'),
        ('sales', '0002_remove_salesplan_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='یکبار تلاش برای خرید'),
        ),
        migrations.AlterUniqueTogether(
            name='sells',
            unique_together={('consumer', 'sale_plan')},
        ),
    ]
