# Generated by Django 3.2.13 on 2023-03-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesplan_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesplan',
            options={'verbose_name': 'طرح فروش', 'verbose_name_plural': 'طرح های فروش'},
        ),
        migrations.RemoveField(
            model_name='sellers',
            name='capacity',
        ),
    ]
