# Generated by Django 4.1.7 on 2023-03-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sells_consumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesplan',
            name='total_sales',
        ),
    ]
