# Generated by Django 3.2.13 on 2023-03-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_auto_20230310_1324'),
        ('sales', '0005_remove_salesplan_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_consumer', to='consumers.consumers', verbose_name='مصرف کننده'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='sale_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sale_plan', to='sales.salesplan', verbose_name='طرح فروش'),
        ),
        migrations.AlterField(
            model_name='sells',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_seller', to='sales.sellers', verbose_name='فروشنده'),
        ),
    ]
