# Generated by Django 3.2.13 on 2023-03-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20230311_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplan',
            name='sellers',
            field=models.ManyToManyField(to='sales.Sellers', verbose_name='فروشندگان طرح'),
        ),
    ]
